### ISSUE TITLE
Binary XML file line #26: Error inflating class com.bitvale.lightprogress.LightProgress

### ISSUE THREAD

**Issue by dondeepak** [bitvale/LightProgress#1]
Binary XML file line #26: Error inflating class com.bitvale.lightprogress.LightProgress

please tell me how to fix this

**Comment by bitvale** [comment]
Can not help you without full stack trace and source code.

**Comment by dondeepak** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.co.list_auto, PID: 29548
    java.lang.RuntimeException: Unable to start activity ComponentInfo{in.co.list_auto/in.co.list_auto.activity.DevicesActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.bitvale.lightprogress.LightProgress
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.bitvale.lightprogress.LightProgress
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.transition.Scene.enter(Scene.java:175)
        at com.android.internal.policy.impl.PhoneWindow.transitionTo(PhoneWindow.java:449)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:392)
        at android.app.Activity.setContentView(Activity.java:2177)
        at in.co.list_auto.activity.DevicesActivity.onCreate(DevicesActivity.java:69)
        at android.app.Activity.performCreate(Activity.java:6093)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.transition.Scene.enter(Scene.java:175) 
        at com.android.internal.policy.impl.PhoneWindow.transitionTo(PhoneWindow.java:449) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:392) 
        at android.app.Activity.setContentView(Activity.java:2177) 
        at in.co.list_auto.activity.DevicesActivity.onCreate(DevicesActivity.java:69) 
        at android.app.Activity.performCreate(Activity.java:6093) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/res/TypedArrayKt;
        at com.bitvale.lightprogress.LightProgress.retrieveAttributes(LightProgress.kt:78)
        at com.bitvale.lightprogress.LightProgress.<init>(LightProgress.kt:69)
        at com.bitvale.lightprogress.LightProgress.<init>(LightProgress.kt:23)
        at com.bitvale.lightprogress.LightProgress.<init>(LightProgress.kt)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.transition.Scene.enter(Scene.java:175) 
        at com.android.internal.policy.impl.PhoneWindow.transitionTo(PhoneWindow.java:449) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:392) 
        at android.app.Activity.setContentView(Activity.java:2177) 
        at in.co.list_auto.activity.DevicesActivity.onCreate(DevicesActivity.java:69) 
        at android.app.Activity.performCreate(Activity.java:6093) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.res.TypedArrayKt" on path: DexPathList[[zip file "/data/app/in.co.list_auto-1/base.apk"],nativeLibraryDirectories=[/data/app/in.co.list_auto-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.bitvale.lightprogress.LightProgress.retrieveAttributes(LightProgress.kt:78) 
        at com.bitvale.lightprogress.LightProgress.<init>(LightProgress.kt:69) 
        at com.bitvale.lightprogress.LightProgress.<init>(LightProgress.kt:23) 
        at com.bitvale.lightprogress.LightProgress.<init>(LightProgress.kt) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.transition.Scene.enter(Scene.java:175) 
        at com.android.internal.policy.impl.PhoneWindow.transitionTo(PhoneWindow.java:449) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:392) 
        at android.app.Activity.setContentView(Activity.java:2177) 
        at in.co.list_auto.activity.DevicesActivity.onCreate(DevicesActivity.java:69) 
        at android.app.Activity.performCreate(Activity.java:6093) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
    	Suppressed: java.lang.ClassNotFoundException: androidx.core.content.res.TypedArrayKt
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 31 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by dondeepak** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:orientation="vertical"
    tools:context="activity.DevicesActivity">
    <com.bitvale.lightprogress.LightProgress
        android:id="@+id/light"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="10dp"
        android:text="Scanning..."
        android:textColor="@color/mapPrimary"
        android:textSize="@dimen/text_size"
        app:light_color="@color/black_transparent" />
  
    <ListView
        android:id="@+id/lvDevices"
        android:layout_width="wrap_content"
        android:layout_height="?android:actionBarSize"
        android:layout_gravity="center"
        android:elevation="@dimen/_5sdp"
        app:layout_anchorGravity="center"
        android:layout_marginTop="@dimen/_10sdp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />




</LinearLayout>

**Comment by bitvale** [comment]
Do you use androidX?

**Comment by dondeepak** [comment]
yes

**Comment by bitvale** [comment]
Can you give your androidX dependencies from build.gradle?

**Comment by dondeepak** [comment]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.android.material:material:1.1.0-alpha10'
    implementation 'com.google.android.gms:play-services:12.0.1'
   
    implementation 'com.intuit.sdp:sdp-android:1.0.4'
    implementation 'com.github.karanchuri:PermissionManager:0.1.0'
    implementation 'com.sdsmdg.tastytoast:tastytoast:0.1.1'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.volley:volley:1.1.0'
 
    implementation 'com.bitvale:lightprogress:1.0.0'
}

**Comment by bitvale** [comment]
Can not found an issue. Does demo project working?

**Comment by dondeepak** [comment]
yes its working without LightProgress xml codes

**Comment by bitvale** [comment]
Demo project from this repository?

**Comment by dondeepak** [comment]
yes

**Comment by KalScv** [comment]
possible add core androidx,

implementation 'androidx.core:core-ktx:1.0.1'

**Comment by dondeepak** [comment]
now its working thank you @KalScv

**Comment by dondeepak** [comment]
is there any way to change light's starting point?
